name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Runs when you push to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=spenderr/shopping-cart
          GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$GIT_SHA .

      # 4️⃣ Push Docker images
      - name: Push Docker images
        run: |
          IMAGE_NAME=spenderr/shopping-cart
          GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GIT_SHA
