name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Runs when you push to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true # This is a good practice to ensure a clean state after the job.

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: spenderr/shopping-cart:latest
